// src/pages/animator/components/SaveButton.tsx
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import LoadingOverlay from '../../../components/LoadingOverlay'
import { useAlert } from '../../../hooks/useAlert'
import { useAnimator } from '../../../hooks/useAnimator'
import { useAnimatorStore } from '../../../hooks/useAnimatorStore'
import { useToast } from '../../../hooks/useToast'
import { SaveState } from '@enums/save-state'
import styles from './ToolbarButton.module.css'

function formatProgress(progress: number): number {
  return Math.min(99, Math.round(progress * 100))
}

export default function SaveButton() {
  const { t } = useTranslation()
  const service = useAnimator()
  const alert = useAlert()
  const toast = useToast()
  const { frames } = useAnimatorStore()
  const [overlayVisible, setOverlayVisible] = useState(false)
  const [overlayMessage, setOverlayMessage] = useState('')

  const openFilenameAlert = async (type: SaveState) => {
    await alert.show({
      header: t('alert_save_animator_header'),
      message: t('alert_save_animator_message'),
      inputs: [
        {
          name: 'filename',
          type: 'text',
          value: `${new Date().toISOString().slice(0, 10)}_stop-motion`,
          placeholder: t('labels_filename'),
        },
      ],
      buttons: [
        { text: t('buttons_cancel'), role: 'cancel' },
        {
          text: t('buttons_save'),
          handler: async ({ filename }) => {
            setOverlayVisible(true)
            setOverlayMessage(t('loader_export_start'))
            try {
              await service.save(filename, type, (state, progress) => {
                setOverlayMessage(
                  t(`encoding_state_${state}`, {
                    progress: formatProgress(progress),
                  }),
                )
              })
            } finally {
              setOverlayVisible(false)
            }
          },
        },
      ],
    })
  }

  const onClick = () => {
    if (frames.length === 0) {
      toast.show({ message: t('toast_animator_save_hint') })
      return
    }
    void alert.show({
      header: t('alert_save_animator_header'),
      message: t('alert_save_animator_message'),
      inputs: [
        {
          name: 'format',
          type: 'radio',
          options: [
            { value: SaveState.draft, label: t('labels_save_as_draft') },
            { value: SaveState.gif, label: t('labels_save_as_gif') },
            { value: SaveState.video, label: t('labels_save_as_video') },
          ],
        },
      ],
      buttons: [
        { text: t('buttons_cancel'), role: 'cancel' },
        {
          text: t('buttons_save'),
          handler: (inputValues) => {
            if (!inputValues.format) {
              toast.show({ message: t('toast_animator_format_hint') })
              return
            }
            // Stage 2 must not be awaited: AlertProvider's handler runs
            // inside its own queue resolution, and awaiting `alert.show`
            // from inside that handler deadlocks the queue (Stage 1's
            // teardown waits for Stage 2's resolve which waits for Stage
            // 1's teardown). `void` lets Stage 1 finish closing before
            // Stage 2 enqueues.
            void openFilenameAlert(inputValues.format as SaveState)
          },
        },
      ],
    })
  }

  return (
    <>
      <button
        type="button"
        className={styles.button}
        aria-label={t('labels_save')}
        data-testid="save-button"
        onClick={onClick}
      >
        <img
          src="/assets/icons/custom/save.svg"
          alt=""
          aria-hidden="true"
          className={styles.icon}
        />
      </button>
      <LoadingOverlay visible={overlayVisible} message={overlayMessage} />
    </>
  )
}

// src/app/pages/animator/components/save-button/save-button.component.ts
import { Component } from '@angular/core';
import { BaseComponent } from '@components/base/base.component';
import { SaveState } from '@enums/save-state';
import { AnimatorService } from '@services/animator/animator.service';
import { BaseService } from '@services/base/base.service';
import { first } from 'rxjs/operators';

export interface ProgressCallback { (state: string, progress: number, time: number): void };

@Component({
  selector: 'app-save-button',
  templateUrl: './save-button.component.html',
  styleUrls: ['./save-button.component.scss'],
})
export class SaveButtonComponent extends BaseComponent {

  constructor(
    public baseService: BaseService,
    private animatorService: AnimatorService
  ) {
    super(baseService);
  }

  async onSave(type: SaveState): Promise<void> {
    this.dismissloading();
    this.baseService.alertService.presentAlert({
      header: this.baseService.translate.instant('alert_save_animator_header'),
      message: this.baseService.translate.instant('alert_save_animator_message'),
      inputs: [
        {
          name: 'filename',
          type: 'text',
          value: `${String(new Date().toISOString()).slice(0, 10)}_stop-motion`,
          placeholder: this.baseService.translate.instant('labels_filename')
        },],
      buttons: [this.baseService.alertService.createCancelButton(), {
        text: this.baseService.translate.instant('buttons_save'),
        handler: async (inputData: any) => {
          await this.baseService.alertService.dismissAlert();
          const loader = await this.presentLoading({
            message: this.baseService.translate.instant('loader_export_start'),
          });

          const progressCallback: ProgressCallback = (state, progress, time) => {
            loader.message = this.baseService.translate.instant(`encoding_state_${state}`, { progress: this.formatProgress(progress) });
          }

          await this.animatorService.save(inputData.filename, type, progressCallback);
          this.dismissloading();
        }
      }]
    });
  }

  async onClick(): Promise<void> {
    const frames = await this.animatorService.getFrames().pipe(first()).toPromise();
    if (frames.length) {
      this.baseService.alertService.presentAlert({
        header: this.baseService.translate.instant('alert_save_animator_header'),
        message: this.baseService.translate.instant('alert_save_animator_message'),
        inputs: [
          {
            name: SaveState.draft,
            type: 'radio',
            label: this.baseService.translate.instant('labels_save_as_draft'),
            value: SaveState.draft,
          },
          {
            name: SaveState.gif,
            type: 'radio',
            label: this.baseService.translate.instant('labels_save_as_gif'),
            value: SaveState.gif,
          },
          {
            name: SaveState.video,
            type: 'radio',
            label: this.baseService.translate.instant('labels_save_as_video'),
            value: SaveState.video,
          },],
        buttons: [this.baseService.alertService.createCancelButton(), {
          text: this.baseService.translate.instant('buttons_save'),
          handler: async (inputData: SaveState) => {
            if (inputData) {
              await this.onSave(inputData);
            } else {
              this.baseService.toastService.presentToast({
                message: this.baseService.translate.instant('toast_animator_format_hint')
              });
            }
          }
        }]
      });
    } else {
      this.baseService.toastService.presentToast({
        message: this.baseService.translate.instant('toast_animator_save_hint')
      });
    }
  }

  private formatProgress(progress: number) {
    let value = Math.round(progress * 100)
    // Some browsers briefly report values above 100%. Cap them here so the UI never shows "101%" while recording finishes.
    return (value <= 99) ? value : 99;
  }
}
